from typing import Any, Dict

from .api_call import ApiCall

class Alias(object):
    api_call: ApiCall
    name: str

    def __init__(self, api_call: ApiCall, name: str) -> None: ...
    def _endpoint_path(self) -> str: ...
    def retrieve(self) -> Dict[str, Any]: ...
    def delete(self) -> Dict[str, Any]: ...
