from typing import Any, Dict

from .api_call import ApiCall

class Key(object):
    key_id: str
    api_call: ApiCall

    def __init__(self, api_call: ApiCall, key_id: str) -> None: ...
    def _endpoint_path(self) -> str: ...
    def retrieve(self) -> Dict[str, Any]: ...
    def delete(self) -> Dict[str, Any]: ...
