from typing import Any, Dict, Optional

from .api_call import ApiCall
from .override import Override

class Overrides(object):
    RESOURCE_PATH: str
    api_call: ApiCall
    collection_name: str
    overrides: Dict[str, Override]

    def __init__(self, api_call: ApiCall, collection_name: str) -> None: ...
    def __getitem__(self, override_id: str) -> Override: ...
    def _endpoint_path(self, override_id: Optional[str] = None) -> str: ...
    def upsert(self, id: str, schema: Dict[str, Any]) -> Dict[str, Any]: ...
    def retrieve(self) -> Dict[str, Any]: ...
